source 'git@code.ds.gome.com.cn:Aeromind-iOS/Specs.git'
source 'git@code.ds.gome.com.cn:Aeromind-iOS/MeiXinSpecs.git'

target 'UIRouter_Example' do
  pod 'UIRouter', :path => '../'

  target 'UIRouter_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
