#!/bin/bash

pod repo push com-meixinspecs ../UIRouter.podspec --use-libraries --sources=git@code.ds.gome.com.cn:Aeromind-iOS/MeiXinSpecs.git,git@code.ds.gome.com.cn:Aeromind-iOS/Specs.git --verbose --allow-warnings
